import type { Metadata } from "next";
import "./globals.css";

import { Providers } from "./providers";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "JJ Constructora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <Providers>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
