export const localidades = {
  departamento: {
    Amazonas: {
      provincias: {
        Chachapoyas: [
          "Asunción",
          "Balsas",
          "Chachapoyas",
          "Cheto",
          "Chiliquín",
          "Chuquibamba",
          "Granada",
          "Huancas",
          "La Jalca",
          "Leimebamba",
          "Levanto",
          "Magdalena",
          "Mariscal Castilla",
          "Molinopampa",
          "Montevideo",
          "Olleros",
          "Quinjalca",
          "San Francisco de Daguas",
          "San Isidro de Maino",
          "Soloco",
          "Sonche",
        ],
        Bagua: [
          "Aramango",
          "Bagua",
          "Copallín",
          "El Parco",
          "Imaza",
          "La Peca",
        ],
        Bongará: [
          "Chisquilla",
          "Churuja",
          "Corosha",
          "Cuispes",
          "Florida",
          "Jazán",
          "Jumbilla",
          "Recta",
          "San Carlos",
          "Shipasbamba",
          "Valera",
          "Yambrasbamba",
        ],
        Condorcanqui: ["El Cenepa", "Nieva", "Río Santiago"],
        Luya: [
          "Camporredondo",
          "Cocabamba",
          "Colcamar",
          "Conila",
          "Inguilpata",
          "Lámud",
          "Longuita",
          "Lonya Chico",
          "Luya",
          "Luya Viejo",
          "María",
          "Ocalli",
          "Ocumal",
          "Pisuquia",
          "Providencia",
          "San Cristóbal",
          "San Francisco del Yeso",
          "San Jerónimo",
          "San Juan de Lopecancha",
          "Santa Catalina",
          "Santo Tomás",
          "Tingo",
          "Trita",
        ],
        "Rodríguez de Mendoza": [
          "Chirimoto",
          "Cochamal",
          "Huambo",
          "Limabamba",
          "Longar",
          "Mariscal Benavides",
          "Milpuc",
          "Omia",
          "San Nicolás",
          "Santa Rosa",
          "Totora",
          "Vista Alegre",
        ],
        Utcubamba: [
          "Bagua Grande",
          "Cajaruro",
          "Cumba",
          "El Milagro",
          "Jamalca",
          "Lonya Grande",
          "Yamón",
        ],
      },
    },
    Ancash: {
      provincias: {
        Huaraz: [
          "Cochabamba",
          "Colcabamba",
          "Huanchay",
          "Huaraz",
          "Independencia",
          "Jangas",
          "La Libertad",
          "Olleros",
          "Pampas Grande",
          "Pariacoto",
          "Pira",
          "Tarica",
        ],
        Aija: ["Aija", "Coris", "Huacllán", "La Merced", "Succha"],
        "Antonio Raymondi": [
          "Aczo",
          "Chaccho",
          "Chingas",
          "Llamellín",
          "Mirgas",
          "San Juan de Rontoy",
        ],
        Asunción: ["Acochaca", "Chacas"],
        Bolognesi: [
          "Abelardo Pardo Lezameta",
          "Antonio Raymondi",
          "Aquia",
          "Cajacay",
          "Canis",
          "Chiquián",
          "Colquioc",
          "Huallanca",
          "Huasta",
          "Huayllacayan",
          "La Primavera",
          "Mangas",
          "Pacllón",
          "San Miguel de Corpanqui",
          "Ticllos",
        ],
        Carhuaz: [
          "Acopampa",
          "Amashca",
          "Anta",
          "Ataquero",
          "Carhuaz",
          "Marcará",
          "Pariahuanca",
          "San Miguel de Aco",
          "Shilla",
          "Tinco",
          "Yungar",
        ],
        "Carlos Fermín Fitzcarrald": ["San Luis", "San Nicolás", "Yauya"],
        Casma: ["Buenavista Alta", "Casma", "Comandante Noel", "Yaután"],
        Corongo: [
          "Aco",
          "Bambas",
          "Corongo",
          "Cusca",
          "La Pampa",
          "Yanac",
          "Yupan",
        ],
        Huari: [
          "Anra",
          "Cajay",
          "Chavín de Huantar",
          "Huacachi",
          "Huacchis",
          "Huachis",
          "Huantar",
          "Huari",
          "Masin",
          "Paucas",
          "Ponto",
          "Rahuapampa",
          "Rapayán",
          "San Marcos",
          "San Pedro de Chana",
          "Uco",
        ],
        Huarmey: ["Cochapeti", "Culebras", "Huarmey", "Huayan", "Malvas"],
        "Mariscal Luzuriaga": [
          "Casca",
          "Eleazar Guzmán Barrón",
          "Fidel Olivas Escudero",
          "Llama",
          "Llumpa",
          "Lucma",
          "Musga",
          "Piscobamba",
        ],
        Ocros: [
          "Acas",
          "Cajamarquilla",
          "Carhuapampa",
          "Cochas",
          "Congas",
          "Llipa",
          "Ocros",
          "San Cristóbal de Rajan",
          "San Pedro",
          "Santiago de Chilcas",
        ],
        Pallasca: [
          "Bolognesi",
          "Cabana",
          "Conchucos",
          "Huacaschuque",
          "Huandoval",
          "Lacabamba",
          "Llapo",
          "Pallasca",
          "Pampas",
          "Santa Rosa",
          "Tauca",
        ],
        Pomabamba: ["Huayllán", "Parobamba", "Pomabamba", "Quinuabamba"],
        Recuay: [
          "Catac",
          "Cotaparaco",
          "Huayllapampa",
          "Llacllin",
          "Marca",
          "Pampas Chico",
          "Pararin",
          "Recuay",
          "Tapacocha",
          "Ticapampa",
        ],
        Santa: [
          "Cáceres del Perú",
          "Chimbote",
          "Coishco",
          "Macate",
          "Moro",
          "Nepeña",
          "Samanco",
          "Santa",
        ],
        Sihuas: [
          "Acobamba",
          "Alfonso Ugarte",
          "Cashapampa",
          "Chingalpo",
          "Huayllabamba",
          "Quiches",
          "Ragash",
          "San Juan",
          "Sicsibamba",
          "Sihuas",
        ],
        Yungay: [
          "Cascapara",
          "Mancos",
          "Matacoto",
          "Quillo",
          "Ranrahirca",
          "Shupluy",
          "Yanama",
          "Yungay",
        ],
      },
    },
    Apurimac: {
      provincias: {
        Abancay: [
          "Abancay",
          "Chacoche",
          "Circa",
          "Curahuasi",
          "Huanipaca",
          "Lambrama",
          "Pichirhua",
          "San Pedro de Cachora",
          "Tamburco",
        ],
        Andahuaylas: [
          "Andahuaylas",
          "Andarapa",
          "Chiara",
          "Huancarama",
          "Huancaray",
          "Huayana",
          "Kaquiabamba",
          "Kishuara",
          "Pacobamba",
          "Pacucha",
          "Pampachiri",
          "Pomacocha",
          "San Antonio de Cachi",
          "San Jerónimo",
          "San Miguel de Chaccrampa",
          "Santa María de Chicmo",
          "Talavera",
          "Tumay Huaraca",
          "Turpo",
        ],
        Antabamba: [
          "Antabamba",
          "El Oro",
          "Huaquirca",
          "Juan Espinoza Medrano",
          "Oropesa",
          "Pachaconas",
          "Sabaino",
        ],
        Aymaraes: [
          "Chalhuanca",
          "Capaya",
          "Caraybamba",
          "Chapimarca",
          "Colcabamba",
          "Cotaruse",
          "Ihuayllo",
          "Justo Apu Sahuaraura",
          "Lucre",
          "Pocohuanca",
          "San Juan de Chacña",
          "Sañayca",
          "Soraya",
          "Tapairihua",
          "Tintay",
          "Toraya",
          "Yanaca",
        ],
        Cotabambas: [
          "Tambobamba",
          "Cotabambas",
          "Coyllurqui",
          "Haquira",
          "Mara",
          "Challhuahuacho",
        ],
        Chincheros: [
          "Chincheros",
          "Anco-Huallo",
          "Cocharcas",
          "Huaccana",
          "Ocobamba",
          "Ongoy",
          "Uranmarca",
          "Ranracancha",
          "Rocchacc",
        ],
        Grau: [
          "Chuquibambilla",
          "Curpahuasi",
          "Gamarra",
          "Huayllati",
          "Mamara",
          "Micaela Bastidas",
          "Pataypampa",
          "Progreso",
          "San Antonio",
          "Santa Rosa",
          "Turpay",
          "Vilcabamba",
          "Virundo",
          "Curasco",
        ],
      },
    },
    Arequipa: {
      provincias: {
        Arequipa: [
          "Arequipa",
          "Alto Selva Alegre",
          "Cayma",
          "Cerro Colorado",
          "Characato",
          "Chiguata",
          "Jacobo Hunter",
          "La Joya",
          "Mariano Melgar",
          "Miraflores",
          "Mollebaya",
          "Paucarpata",
          "Pocsi",
          "Polobaya",
          "Quequeña",
          "Sabandía",
          "Sachaca",
          "San Juan de Siguas",
          "San Juan de Tarucani",
          "Santa Isabel de Siguas",
          "Santa Rita de Siguas",
          "Socabaya",
          "Tiabaya",
          "Uchumayo",
          "Vitor",
          "Yanahuara",
          "Yarabamba",
          "Yura",
        ],
        Camana: [
          "Camaná",
          "José María Quimper",
          "Mariscal Cáceres",
          "Nicolás de Piérola",
          "Ocoña",
          "Quilca",
          "Samuel Pastor",
        ],
        Caraveli: [
          "Acarí",
          "Atico",
          "Atiquipa",
          "Bella Unión",
          "Cahuacho",
          "Caravelí",
          "Chala",
          "Chaparra",
          "Huanuhuanu",
          "Jaquí",
          "Lomas",
          "Quicacha",
          "Yauca",
        ],
        Castilla: [
          "Aplao",
          "Andagua",
          "Ayo",
          "Chachas",
          "Chilcaymarca",
          "Choco",
          "Huancarqui",
          "Machaguay",
          "Orcopampa",
          "Pampacolca",
          "Tipán",
          "Uñón",
          "Uraca",
          "Viraco",
        ],
        Caylloma: [
          "Chivay",
          "Achoma",
          "Cabanaconde",
          "Callalli",
          "Caylloma",
          "Coporaque",
          "Huambo",
          "Huanca",
          "Ichupampa",
          "Lari",
          "Lluta",
          "Maca",
          "Madrigal",
          "San Antonio de Chuca",
          "Sibayo",
          "Tapay",
          "Tisco",
          "Tuti",
          "Yanque",
        ],
        Condesuyos: [
          "Chuquibamba",
          "Andaray",
          "Cayarani",
          "Chichas",
          "Iray",
          "Río Grande",
          "Salamanca",
          "Yanaquihua",
        ],
        Islay: [
          "Mollendo",
          "Cocachacra",
          "Dean Valdivia",
          "Islay",
          "Mejía",
          "Punta de Bombón",
        ],
        "La Union": [
          "Cotahuasi",
          "Alca",
          "Charcana",
          "Huaynacotas",
          "Pampamarca",
          "Puyca",
          "Quechualla",
          "Sayla",
          "Tauria",
          "Tomepampa",
          "Toro",
        ],
      },
    },
    Ayacucho: {
      provincias: {
        Huamanga: [
          "Ayacucho",
          "Acocro",
          "Acos Vinchos",
          "Carmen Alto",
          "Chiara",
          "Jesús Nazareno",
          "Ocros",
          "Pacaycasa",
          "Quinua",
          "San José de Ticllas",
          "San Juan Bautista",
          "Santiago de Pischa",
          "Socos",
          "Tambillo",
          "Vinchos",
        ],
        Cangallo: [
          "Cangallo",
          "Chuschi",
          "Los Morochucos",
          "María Parado de Bellido",
          "Paras",
          "Totos",
        ],
        "Huanca Sancos": [
          "Sancos",
          "Carapo",
          "Sacsamarca",
          "Santiago de Lucanamarca",
        ],
        Huanta: [
          "Huanta",
          "Ayahuanco",
          "Huamanguilla",
          "Iguain",
          "Luricocha",
          "Santillana",
          "Sivia",
          "Llochegua",
          "Canayre",
          "Uchuraccay",
          "Pucacolpa",
          "Chaca",
        ],
        "La Mar": [
          "San Miguel",
          "Anco",
          "Ayna",
          "Chilcas",
          "Chungui",
          "Luis Carranza",
          "Santa Rosa",
          "Tambo",
          "Samugari",
          "Anchihuay",
          "Oronccoy",
        ],
        Lucanas: [
          "Puquio",
          "Aucara",
          "Cabana",
          "Carmen Salcedo",
          "Chaviña",
          "Chipao",
          "Huac-Huas",
          "Laramate",
          "Leoncio Prado",
          "Llauta",
          "Lucanas",
          "Ocaña",
          "Otoca",
          "Saisa",
          "San Cristóbal",
          "San Juan",
          "San Pedro",
          "San Pedro de Palco",
          "Sancos",
          "Santa Ana de Huaycahuacho",
          "Santa Lucia",
        ],
        Parinacochas: [
          "Coracora",
          "Chumpi",
          "Coronel Castañeda",
          "Pacapausa",
          "Pullo",
          "Puyusca",
          "San Francisco de Ravacayco",
          "Upahuacho",
        ],
        "Paucar del Sara Sara": [
          "Pausa",
          "Colta",
          "Corculla",
          "Lampa",
          "Marcabamba",
          "Oyolo",
          "Pararca",
          "San Javier de Alpabamba",
          "San José de Ushua",
          "Sara Sara",
        ],
        Sucre: [
          "Querobamba",
          "Belén",
          "Chalcos",
          "Chilcayoc",
          "Huacaña",
          "Morcolla",
          "Paico",
          "San Pedro de Larcay",
          "San Salvador de Quije",
          "Santiago de Paucaray",
          "Soras",
        ],
        "Víctor Fajardo": [
          "Huancapi",
          "Alcamenca",
          "Apongo",
          "Asquipata",
          "Canaria",
          "Cayara",
          "Colca",
          "Huamanquiquia",
          "Huancaraylla",
          "Huaya",
          "Sarhua",
          "Vilcanchos",
        ],
        "Vilcas Huamán": [
          "Vilcas Huamán",
          "Accomarca",
          "Carhuanca",
          "Concepción",
          "Huambalpa",
          "Independencia",
          "Saurama",
          "Vischongo",
        ],
      },
    },
    Cajamarca: {
      provincias: {
        Cajamarca: [
          "Cajamarca",
          "Asunción",
          "Chetilla",
          "Cospán",
          "Encañada",
          "Jesús",
          "Llacanora",
          "Los Baños del Inca",
          "Magdalena",
          "Matara",
          "Namora",
          "San Juan",
        ],
        Cajabamba: ["Cajabamba", "Cachachi", "Condebamba", "Sitacocha"],
        Celendín: [
          "Celendín",
          "Chumuch",
          "Cortegana",
          "Huasmin",
          "Jorge Chávez",
          "José Gálvez",
          "Miguel Iglesias",
          "Oxamarca",
          "Sorochuco",
          "Sucre",
          "Utco",
          "La Libertad de Pallán",
        ],
        Chota: [
          "Chota",
          "Anguía",
          "Chadin",
          "Chiguirip",
          "Chimban",
          "Choropampa",
          "Cochabamba",
          "Conchan",
          "Huambos",
          "Lajas",
          "Llama",
          "Miracosta",
          "Paccha",
          "Pion",
          "Querocoto",
          "San Juan de Licupis",
          "Tacabamba",
          "Tocmoche",
        ],
        Contumazá: [
          "Contumazá",
          "Chilete",
          "Cupisnique",
          "Guzmango",
          "San Benito",
          "Santa Cruz de Toledo",
          "Tantarica",
          "Yonán",
        ],
        Cutervo: [
          "Cutervo",
          "Callayuc",
          "Choros",
          "Cujillo",
          "La Ramada",
          "Pimpingos",
          "Querocotillo",
          "San Andrés de Cutervo",
          "San Juan de Cutervo",
          "San Luis de Lucma",
          "Santa Cruz",
          "Santo Domingo de la Capilla",
          "Santo Tomás",
          "Socota",
          "Toribio Casanova",
        ],
        Hualgayoc: ["Bambamarca", "Chugur", "Hualgayoc"],
        Jaén: [
          "Jaén",
          "Bellavista",
          "Chontalí",
          "Colasay",
          "Huabal",
          "Las Pirias",
          "Pomahuaca",
          "Pucará",
          "Sallique",
          "San Felipe",
          "San José del Alto",
          "Santa Rosa",
        ],
        "San Ignacio": [
          "San Ignacio",
          "Chirinos",
          "Huarango",
          "La Coipa",
          "Namballe",
          "San José de Lourdes",
          "Tabaconas",
        ],
        "San Marcos": [
          "San Marcos",
          "Chancay",
          "Eduardo Villanueva",
          "Gregorio Pita",
          "Ichocán",
          "José Sabogal",
          "Pedro Gálvez",
        ],
        "San Miguel": [
          "San Miguel",
          "Bolívar",
          "Calquis",
          "Catilluc",
          "El Prado",
          "La Florida",
          "Llapa",
          "Nanchoc",
          "Niepos",
          "San Gregorio",
          "San Silvestre de Cochan",
          "Tongod",
          "Unión Agua Blanca",
        ],
        "San Pablo": ["San Pablo", "San Bernardino", "San Luis", "Tumbaden"],
        "Santa Cruz": [
          "Santa Cruz",
          "Andabamba",
          "Catache",
          "Chancaybaños",
          "La Esperanza",
          "Ninabamba",
          "Pulan",
          "Saucepampa",
          "Sexi",
          "Uticyacu",
          "Yauyucan",
        ],
      },
    },
    Cusco: {
      provincias: {
        Acomayo: [
          "Acomayo",
          "Acopia",
          "Acos",
          "Mosoc Llacta",
          "Pomacanchi",
          "Rondocan",
          "Sangarará",
        ],
        Anta: [
          "Anta",
          "Ancahuasi",
          "Cachimayo",
          "Chinchaypujio",
          "Huarocondo",
          "Limatambo",
          "Mollepata",
          "Pucyura",
          "Zurite",
        ],
        Calca: [
          "Calca",
          "Coya",
          "Lamay",
          "Lares",
          "Pisac",
          "San Salvador",
          "Taray",
          "Yanatile",
        ],
        Canas: [
          "Yanaoca",
          "Checca",
          "Kunturkanki",
          "Langui",
          "Layo",
          "Pampamarca",
          "Quehue",
          "Túpac Amaru",
        ],
        Canchis: [
          "Sicuani",
          "Checacupe",
          "Combapata",
          "Marangani",
          "Pitumarca",
          "San Pablo",
          "San Pedro",
          "Tinta",
        ],
        Chumbivilcas: [
          "Santo Tomás",
          "Capacmarca",
          "Chamaca",
          "Colquemarca",
          "Livitaca",
          "Llusco",
          "Quiñota",
          "Velille",
        ],
        Cusco: [
          "Cusco",
          "Ccorca",
          "Poroy",
          "San Jerónimo",
          "San Sebastián",
          "Santiago",
          "Saylla",
          "Wanchaq",
        ],
        Espinar: [
          "Espinar",
          "Condoroma",
          "Coporaque",
          "Ocoruro",
          "Pallpata",
          "Pichigua",
          "Suykutambo",
          "Alto Pichigua",
        ],
        "La Convención": [
          "Santa Ana",
          "Echarate",
          "Huayopata",
          "Maranura",
          "Ocobamba",
          "Pichari",
          "Quellouno",
          "Kimbiri",
          "Santa Teresa",
          "Vilcabamba",
          "Inkawasi",
          "Villa Virgen",
          "Villa Kintiarina",
        ],
        Paruro: [
          "Paruro",
          "Accha",
          "Ccapi",
          "Colcha",
          "Huanoquite",
          "Omacha",
          "Paccaritambo",
          "Pillpinto",
          "Yaurisque",
        ],
        Paucartambo: [
          "Paucartambo",
          "Caicay",
          "Challabamba",
          "Colquepata",
          "Huancarani",
          "Kosñipata",
        ],
        Quispicanchi: [
          "Urcos",
          "Andahuaylillas",
          "Camanti",
          "Ccarhuayo",
          "Ccatca",
          "Cusipata",
          "Huaro",
          "Lucre",
          "Marcapata",
          "Ocongate",
          "Oropesa",
          "Quiquijana",
        ],
        Urubamba: [
          "Urubamba",
          "Chinchero",
          "Huayllabamba",
          "Machupicchu",
          "Maras",
          "Ollantaytambo",
          "Yucay",
        ],
      },
    },
    Huancavelica: {
      provincias: {
        Huancavelica: [
          "Huancavelica",
          "Acobambilla",
          "Acoria",
          "Conayca",
          "Cuenca",
          "Huachocolpa",
          "Huayllahuara",
          "Izcuchaca",
          "Laria",
          "Manta",
          "Mariscal Cáceres",
          "Moya",
          "Nuevo Occoro",
          "Palca",
          "Pilchaca",
          "Vilca",
          "Yauli",
          "Ascensión",
        ],
        Acobamba: [
          "Acobamba",
          "Andabamba",
          "Anta",
          "Caja",
          "Marcas",
          "Paucara",
          "Pomacocha",
          "Rosario",
        ],
        Angaraes: [
          "Lircay",
          "Anchonga",
          "Callanmarca",
          "Ccochaccasa",
          "Chincho",
          "Congalla",
          "Huanca-Huanca",
          "Huayllay Grande",
          "Julcamarca",
          "San Antonio de Antaparco",
          "Santo Tomás de Pata",
          "Secclla",
        ],
        Castrovirreyna: [
          "Castrovirreyna",
          "Arma",
          "Aurahua",
          "Capillas",
          "Chupamarca",
          "Cocas",
          "Huachos",
          "Huamatambo",
          "Mollepampa",
          "San Juan",
          "Santa Ana",
          "Tantara",
          "Ticrapo",
        ],
        Churcampa: [
          "Churcampa",
          "Anco",
          "Chinchihuasi",
          "El Carmen",
          "La Merced",
          "Locroja",
          "Pachamarca",
          "Paucarbamba",
          "San Miguel de Mayocc",
          "San Pedro de Coris",
        ],
        Huaytará: [
          "Huaytará",
          "Ayavi",
          "Córdova",
          "Huayacundo Arma",
          "Laramarca",
          "Ocoyo",
          "Pilpichaca",
          "Querco",
          "Quito-Arma",
          "San Antonio de Cusicancha",
          "San Francisco de Sangayaico",
          "San Isidro",
          "Santiago de Chocorvos",
          "Santiago de Quirahuara",
          "Santo Domingo de Capillas",
          "Tambo",
        ],
        Tayacaja: [
          "Pampas",
          "Acostambo",
          "Acraquia",
          "Ahuaycha",
          "Colcabamba",
          "Daniel Hernández",
          "Huachocolpa",
          "Huaribamba",
          "Ñahuimpuquio",
          "Pazos",
          "Quichuas",
          "Quishuar",
          "Salcabamba",
          "Salcahuasi",
          "San Marcos de Rocchac",
          "Surcubamba",
          "Tintay Puncu",
        ],
      },
    },
    Huánuco: {
      provincias: {
        Huánuco: [
          "Huánuco",
          "Amarilis",
          "Chinchao",
          "Churubamba",
          "El Molino",
          "Huánuco",
          "Pillco Marca",
          "San Francisco de Cayran",
          "San Pedro de Chaulán",
          "Yarowilca",
        ],
        "Leoncio Prado": [
          "Tingo María",
          "Panao",
          "Rupa Rupa",
          "Luyando",
          "Pucayacu",
          "Pucallpillo",
        ],
        "Dos de Mayo": [
          "La Unión",
          "Churubamba",
          "San Pedro de Chaulán",
          "Yarowilca",
        ],
        Huamalíes: [
          "Llata",
          "Jircan",
          "Chavín de Pariarca",
          "Pillco Marca",
          "San Juan de Huánuco",
        ],
        Marañón: [
          "Huacrachuco",
          "Chinchao",
          "San Juan de Rontoy",
          "San Miguel de Cauri",
        ],
        Pachitea: [
          "Panao",
          "Pillco Marca",
          "San Francisco de Cayran",
          "San Pedro de Chaulán",
        ],
        "Rupa Rupa": ["Rupa Rupa", "San Juan de Rontoy", "San Miguel de Cauri"],
        Yarowilca: ["Yarowilca", "Chinchao", "San Pedro de Chaulán"],
      },
    },

        

  },
};


export const departaments=[
  "Amazonas",
  "Áncash",
  "Apurímac",
  "Arequipa",
  "Ayacucho",
  "Cajamarca",
  "Callao",
  "Cusco",
  "Huancavelica",
  "Huánuco",
  "Ica",
  "Junín",
  "La Libertad",
  "Lambayeque",
  "Lima",
  "Loreto",
  "Madre de Dios",
  "Moquegua",
  "Pasco",
  "Piura",
  "Puno",
  "San Martín",
  "Tacna",
  "Tumbes",
  "Ucayali"
]



export const Localidades = [
  {
    "departamento": "Amazonas",
    "provincias": ["Chachapoyas", "Bagua", "Bongará", "Condorcanqui", "Luya", "Rodríguez de Mendoza", "Utcubamba"]
  },
  {
    "departamento": "Áncash",
    "provincias": ["Huaraz", "Aija", "Antonio Raymondi", "Asunción", "Bolognesi", "Carhuaz", "Carlos Fermín Fitzcarrald", "Casma", "Corongo", "Huari", "Huarmey", "Huaylas", "Mariscal Luzuriaga", "Ocros", "Pallasca", "Pomabamba", "Recuay", "Santa", "Sihuas", "Yungay"]
  },
  {
    "departamento": "Apurímac",
    "provincias": ["Abancay", "Andahuaylas", "Antabamba", "Aymaraes", "Cotabambas", "Chincheros", "Grau"]
  },
  {
    "departamento": "Arequipa",
    "provincias": ["Arequipa", "Camaná", "Caravelí", "Castilla", "Caylloma", "Condesuyos", "Islay", "La Unión"]
  },
  {
    "departamento": "Ayacucho",
    "provincias": ["Huamanga", "Cangallo", "Huanca Sancos", "Huanta", "La Mar", "Lucanas", "Parinacochas", "Páucar del Sara Sara", "Sucre", "Víctor Fajardo", "Vilcas Huamán"]
  },
  {
    "departamento": "Cajamarca",
    "provincias": ["Cajamarca", "Cajabamba", "Celendín", "Chota", "Contumazá", "Cutervo", "Hualgayoc", "Jaén", "San Ignacio", "San Marcos", "San Miguel", "San Pablo", "Santa Cruz"]
  },
  {
    "departamento": "Callao",
    "provincias": ["Callao"]
  },
  {
    "departamento": "Cusco",
    "provincias": ["Cusco", "Acomayo", "Anta", "Calca", "Canas", "Canchis", "Chumbivilcas", "Espinar", "La Convención", "Paruro", "Paucartambo", "Quispicanchi", "Urubamba"]
  },
  {
    "departamento": "Huancavelica",
    "provincias": ["Huancavelica", "Acobamba", "Angaraes", "Castrovirreyna", "Churcampa", "Huaytará", "Tayacaja"]
  },
  {
    "departamento": "Huánuco",
    "provincias": ["Huánuco", "Ambo", "Dos de Mayo", "Huacaybamba", "Huamalíes", "Leoncio Prado", "Marañón", "Pachitea", "Puerto Inca", "Lauricocha", "Yarowilca"]
  },
  {
    "departamento": "Ica",
    "provincias": ["Ica", "Chincha", "Nazca", "Palpa", "Pisco"]
  },
  {
    "departamento": "Junín",
    "provincias": ["Huancayo", "Concepción", "Chanchamayo", "Jauja", "Junín", "Satipo", "Tarma", "Yauli", "Chupaca"]
  },
  {
    "departamento": "La Libertad",
    "provincias": ["Trujillo", "Ascope", "Bolívar", "Chepén", "Gran Chimú", "Julcán", "Otuzco", "Pacasmayo", "Pataz", "Sánchez Carrión", "Santiago de Chuco", "Virú"]
  },
  {
    "departamento": "Lambayeque",
    "provincias": ["Chiclayo", "Ferreñafe", "Lambayeque"]
  },
  {
    "departamento": "Lima",
    "provincias": ["Lima", "Barranca", "Cajatambo", "Canta", "Cañete", "Huaral", "Huarochirí", "Huaura", "Oyón", "Yauyos"]
  },
  {
    "departamento": "Loreto",
    "provincias": ["Maynas", "Alto Amazonas", "Datem del Marañón", "Loreto", "Mariscal Ramón Castilla", "Putumayo", "Requena", "Ucayali"]
  },
  {
    "departamento": "Madre de Dios",
    "provincias": ["Tambopata", "Manu", "Tahuamanu"]
  },
  {
    "departamento": "Moquegua",
    "provincias": ["Mariscal Nieto", "General Sánchez Cerro", "Ilo"]
  },
  {
    "departamento": "Pasco",
    "provincias": ["Pasco", "Daniel Alcides Carrión", "Oxapampa"]
  },
  {
    "departamento": "Piura",
    "provincias": ["Piura", "Ayabaca", "Huancabamba", "Morropón", "Paita", "Sechura", "Sullana", "Talara"]
  },
  {
    "departamento": "Puno",
    "provincias": ["Puno", "Azángaro", "Carabaya", "Chucuito", "El Collao", "Huancané", "Lampa", "Melgar", "Moho", "San Antonio de Putina", "San Román", "Sandia", "Yunguyo"]
  },
  {
    "departamento": "San Martín",
    "provincias": ["Moyobamba", "Bellavista", "El Dorado", "Huallaga", "Lamas", "Mariscal Cáceres", "Picota", "Rioja", "San Martín", "Tocache"]
  },
  {
    "departamento": "Tacna",
    "provincias": ["Tacna", "Candarave", "Jorge Basadre", "Tarata"]
  },
  {
    "departamento": "Tumbes",
    "provincias": ["Tumbes", "Contralmirante Villar", "Zarumilla"]
  },
  {
    "departamento": "Ucayali",
    "provincias": ["Coronel Portillo", "Atalaya", "Padre Abad", "Purús"]
  }
]
